@node Overview
@chapter Overview

@command{libclut} is C library for manipulating colour
lookup tables. @command{libclut} is used by including
the header @file{<libclut.h>}. Some functionality also
requires that the objects be linked with @option{-lclut}.

@command{libclut} is designed to work well with
@command{libgamma} and @command{libcoopgamma}, but does
not require that either is used for any of its
[@command{libclut}'s] functionality.

